site_name: 个人笔记
site_url: https://zhengzihao1998.github.io./
site_author: zhengzihao
site_description: 笔记

# Repository
repo_name: zhengzihao27/zhengzihao27.github.io
repo_url: https://github.com/zhengzihao27/zhengzihao27.github.io


copyright: Copyright &copy; 2016 - 2024 Zhengzihao




theme:
  name: material
  # custom_dir: material/overrides
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.expand
    - navigation.sections
    - navigation.footer
    - navigation.top    # 返回顶部
    - navigation.tracking
    - navigation.prune

    - content.tabs.link # 内容选项卡根据其标签进行链接
    - content.code.copy # 代码复制功能
    - content.code.select # 代码选中
    - content.tooltips

    - search.highlight
    - search.share
    - search.suggest
    


######### Color palette toggle #######
######### light mode & dark mode #####
  palette: 
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
#######################################

  icon:
    annotation: material/arrow-right-circle 
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
    repo: fontawesome/brands/github # 存储库图标


nav:
  - 主页: index.md
  - 笔记: 
      - blog/index.md
  - 关于我: about.md


plugins:
  - search:
      separator: '[\s\u200b\-]'
  - blog:
      archive_name: Archive
      archive_toc: false
      categories_name: Categories
      categories_toc: true
      blog_toc: true
      pagination_per_page: 5
  - tags
  - minify:
      minify_html: true
  # 显示文档的最后更新和创建日期
  # - git-revision-date-localized:  
  #     enable_creation_date: true
  #     type: timeago


markdown_extensions:

  # LaTeX、MathML、AsciiMath
  - pymdownx.arithmatex:
      generic: true

  # 图片      
  - attr_list 
  - md_in_html

  # 警告
  - admonition
  - pymdownx.details

  # Icons, Emojis
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji

  # 注解
  - pymdownx.superfences

  # 数据表
  - tables


  # 列表
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

  # code blocks
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  

  # Content tabs
  - pymdownx.tabbed:
      alternate_style: true



extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css
